### ISSUE TITLE
github build artifacts are currently expired

### ISSUE THREAD

**Issue by hiinaspace** [YPares/arpligner#18]
The artifacts in the latest builds (4 months ago) are expired so we can't download it, e.g. https://github.com/YPares/arpligner/actions/runs/4098641585 .

**Comment by YPares** [comment]
Hello :) I just re-ran the builds. I should put in place a better a way to download nightlies (I should have more time to work on Arpligner in the coming weeks)

**Comment by YPares** [comment]
Hello :) The builds are available on itch.io now => https://ywen.itch.io/arpligner
